//将导航HTML写入页面，请将链接补全

document.writeln("<footer>");
document.writeln("	<div class=\'main-container\'>");
document.writeln("		<dl>");
document.writeln("			<dt><a href=\'#\'>关于XPM</a></dt>");
document.writeln("			<dt><a href=\'#\'>视频宣传</a></dt>");
document.writeln("			<dt><a href=\'#\'>联系我们</a></dt>");
document.writeln("			<dt><a href=\'#\'>微博</a></dt>");
document.writeln("		</dl>");
document.writeln("		<dl>");
document.writeln("			<dt><a href=\'#\'>XPM地址</a></dt>");
document.writeln("			<dd class=\'tGrey\'>湖南省长沙岳麓区洋湖街道潇湘南路一段387号</dd>");
document.writeln("		</dl>");
document.writeln("		<dl>");
document.writeln("			<dt><a href=\'#\'>XPM邮箱</a></dt>");
document.writeln("			<dd class=\'tGrey\'>xzlmuseum@163.com</dd>");
document.writeln("		</dl>");
document.writeln("		<dl>");
document.writeln("			<dt><a href=\'#\'>联系电话</a></dt>");
document.writeln("			<dd class=\'tGrey\'>0731- 88991518</dd>");
document.writeln("		</dl>");
document.writeln("		<div class=\'logo\'>");
document.writeln("			<a class=\'blogo\' target=\'_blank\' href=\'https://weixin.qq.com/\'><img src=\'../img/blogo4.png\' /><img src=\'../img/blogo4-on.png\' /></a>");
document.writeln("			<a class=\'blogo\' target=\'_blank\' href=\'https://weibo.com/\'><img src=\'../img/blogo3.png\' /><img src=\'../img/blogo3-on.png\' /></a>");
document.writeln("			<a class=\'blogo\' target=\'_blank\' href=\'http://www.youku.com/\'><img src=\'../img/blogo1.png\' /><img src=\'../img/blogo1-on.png\' /></a>");
document.writeln("			<a class=\'blogo\' target=\'_blank\' href=\'https://www.toutiao.com/\'><img src=\'../img/blogo2.png\' /><img src=\'../img/blogo2-on.png\' /></a>");
document.writeln("		</div>");
document.writeln("		<div class=\'orcode\'>");
document.writeln("			<div><img src=\'../img/login/orcode.jpg\' /></div>");
document.writeln("			<h4>XPM公众号</h4>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<div class=\'backup\'>京ICP备08004966号-2.</div>");
document.writeln("</footer>");